blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://github.com/luc-github/ESP3D/wiki
    about: The Wiki has lot of informations.
  - name: F.A.Q. (Frequent asked questions)
    url: https://github.com/luc-github/ESP3D/issues?utf8=%E2%9C%93&q=label%3AFAQ
    about: The usual questions / problems meet and their solution  
  - name: Gitter chat
    url: https://gitter.im/luc-github/ESP3D
    about: Join the gitter for support and discussion.
